---
services: docker

env:
  - distro: centos7
    playbook: test.yml

before_install:
  - 'docker pull geerlingguy/docker-${distro}-ansible:latest'

script:
  - export container_id=$(date +%s)
  - export cleanup=false

  # Download test shim (ripped from Jeff Geerling)
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/derekbelrose/239c91e8aa62a8d72f4a9e3a0b31d658/raw/4298947d0b1bb602913bbf46102abf43f5fe7dce/ansible-role-test.sh
  - chmod +x ${PWD}/tests/test.sh

  # Run Tests
  - ${PWD}/tests/test.sh

notifications:
  webhooks:
      urls:
        - https://galaxy.ansible.com/api/v1/notifications/
      on_success: always
      on_failure: never
      email:
        on_failure: never
        on_success: never
