---
# tasks file for jhu-role-wordpress

- name: Create directory
  file:
    path: "{{ wordpress_home }}"
    state: directory
    mode: 0755
    owner: ops
    group: ops

- name: Unarchive wordpress download and create hidden file
  unarchive:
    src: "{{ wordpress_url }}"
    dest: "{{ wordpress_home }}/../"
    owner: ops
    group: ops
    remote_src: True
    creates: "{{ wordpress_url }}/.{{ wordpress_version }}"
  notify: touch version file
